### ISSUE TITLE
Readme Step 1:  google keys

### ISSUE THREAD

**Issue by ag00se** [blowdart/AspNetAuthenticationWorkshop#3]
Thank you for providing a nice overview about this topic.

I was first just using the readme page and there in Step1 in the code example the used properties for the google options do not exist. (ConsumerKey, ConsumerSecret)

In the Step 1 folder you have the correct properties specified. (ClientId, ClientSecret)
Maybe you want to adjust that.

**Comment by blowdart** [comment]
Oops, thank you.
