### ISSUE TITLE
CORS and Integrated Authentication

### ISSUE THREAD

**Issue by Rainman21** [blowdart/AspNetAuthenticationWorkshop#4]
Was at MSBuild 2019, and your peers recommended I post the issue here...  We are running WebAPI with CORS 'AllowAll'  for inside the firewall services consumed by several servers (services run on build farm computers,  web servers either local host, or production/preproduction/dev web servers).  
Everything worked great until we enabled  Integrated Auth.  We realized that PUT/DELETE failing due to CORS, despite working OK when not using Authentication.  **From what I read, the CORS under IntegratedAuth does not honor * origin, but instead specific origin URL only.**  
_What I'm trying to do is to use MiddleWare class to capture the preflight request URL, and inject into the preflight response header so that CORS is satisfied, but several of us have been stuck for days hitting our heads against the wall._

I'd love an example that can enable a PUT or DELETE verb on integrated auth from an ajax call in a page served from host running on a domain member computer (IISExpress, NodeJS or whatever) and have it successfull navigate the CORS preflight and execute the PUT or DELETE method.  Ideally, the CORE API would work as expected, regardless of whether Integrated AUTH is being used or not.

Any thoughts?

**Comment by blowdart** [comment]
This so wasn't the right place to ask. The main aspnet repo would be better (as you can see from how long it took me to respond.) There have been a bunch of CORS questions on Windows Auth there, and it boils down to "Use the IIS CORS support and not any aspnet core middlware"
